language:
  ruby

rvm:
  - '2.1'
  - '2.2'
  - '2.3'
  - '2.4'
  - '2.5'
  - ruby-head
  - jruby-9.1
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

  fast_finish:
    true

script:
  rake spec

install:
  - gem install hen
  - rake gem:dependencies:install
  - gem install --prerelease nuggets

sudo:
  false
